name: Backend-CICD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install -r requirements.txt
      - name: migrate database
        run: |
          python3 manage.py migrate
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        uses: appleboy/ssh-ation@master
        with:
          host: ${{secrets.SERVER_IP}}
          port: ${{secrets.SERVER_PORT}}
          username: ${{secrets.SERVER_USERNAME}}\
          key: ${{secrets.SERVER_SSHKEY}}
          script: |
            docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
            docker pull kaesea/django-ci:v1.0
            cd ${{secrets.SERVER_PROJWECT_PATH}}
            docker run -d -p 8000:8000 --rm kaesea/django-ci:v1.0
