name: django ci workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_app:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: install_requirements
        run: pip3 install -r requirements.txt
        shell: bash

      - name: migrate_app
        run: python3 manage.py migrate
        shell: bash
   
      #- name: run_app
       # run: python3 manage.py runserver
        #shell: bash
  # dockerize_app:

